# SPDX-FileCopyrightText: 2023 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: klock
release:
  github:
    owner: jilleJr
    name: kubectl-klock
builds:
  - id: klock
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - arm64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: main.go
    ldflags: -s -w
      -X github.com/jilleJr/kubectl-klock/pkg/version.version=

snapcrafts:
  - id: klock
    name: klock
    license: GPL-3.0-or-later
    description: |
      Kubectl plugin that watches resources and prints them in a human-readable manner.
      Very similar to `kubectl get`, but with live updates.
    summary: Kubectl plugin that watches resources

    grade: devel # stable | devel
    confinement: strict # strict | devmode | classic
    apps:
      kubectl-klock:
        command: bin/kubectl-klock
        plugs:
          - home
          - network

archives:
  - id: klock
    builds:
    - klock
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
