# SPDX-FileCopyrightText: 2023 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: kubectl-klock
release:
  github:
    owner: jilleJr
    name: kubectl-klock
builds:
  - goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - arm64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: main.go
    ldflags: -s -w -X main.version={{ .Version }}

snapcrafts:
  - name: klock
    license: GPL-3.0-or-later
    description: |
      Kubectl plugin that watches resources and prints them in a human-readable manner.
      Very similar to `kubectl get`, but with live updates.
    summary: Kubectl plugin that watches resources

    grade: devel # stable | devel
    confinement: strict # strict | devmode | classic

    extra_files:
      - source: bin/kubectl-klock.completion.bash.license
        destination: bin/klock.kubectl-klock.completion.bash.license
        mode: 0644
      - source: bin/kubectl_complete-klock
        destination: kubectl_complete-klock
        mode: 0755
      - source: LICENSES
        destination: LICENSES
        mode: 0644

    apps:
      kubectl-klock:
        command: kubectl-klock
        aliases:
          - kubectl-klock # instead of klock.kubectl-klock
        plugs:
          - home
          - network
        completer: bin/kubectl-klock.completion.bash

      # Special program that kubectl looks for to do completion from
      # when running "kubectl klock <TAB>"
      kubectl-complete:
        command: kubectl_complete-klock
        aliases:
          - kubectl_complete-klock # instead of klock.kubectl-complete

archives:
  - builds:
    - kubectl-klock
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
