# SPDX-FileCopyrightText: 2023 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: klock
spec:
  version: {{ .TagName }}
  homepage: https://github.com/jilleJr/kubectl-klock
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/klock_linux_amd64.tar.gz
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/klock_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "./klock"
      to: "."
    - from: LICENSE
      to: "."
    bin: "klock"

  - selector:
      matchLabels:
        os: linux
        arch: "386"
    uri: https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/klock_linux_386.tar.gz
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/klock_linux_386.tar.gz" .TagName }}
    files:
    - from: "./klock"
      to: "."
    - from: LICENSE
      to: "."
    bin: "klock"

  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/klock_darwin_amd64.tar.gz
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/klock_darwin_amd64.tar.gz" .TagName }}
    sha256: ""
    files:
    - from: "./klock"
      to: "."
    - from: LICENSE
      to: "."
    bin: "klock"

  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/klock_windows_amd64.zip
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/klock_windows_amd64.zip" .TagName }}
    sha256: ""
    files:
    - from: "/klock.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "klock.exe"

  - selector:
      matchLabels:
        os: windows
        arch: "386"
    uri: https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/klock_windows_386.zip
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/klock_windows_386.zip" .TagName }}
    sha256: ""
    files:
    - from: "/klock.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "klock.exe"

  shortDescription: Watches resources
  description: |
    Usage:
      $ kubectl klock <resource> [name]
      This plugin watches resources and prints them in a human-readable manner. Very similar to `kubectl get`, but with live updates.
      Read more documentation at: https://github.com/jilleJr/kubectl-klock
