# SPDX-FileCopyrightText: 2023 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: klock
spec:
  version: {{ .TagName }}
  homepage: https://github.com/jilleJr/kubectl-klock
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/kubectl-klock_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "./kubectl-klock"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-klock"

  - selector:
      matchLabels:
        os: linux
        arch: "386"
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/kubectl-klock_linux_386.tar.gz" .TagName }}
    files:
    - from: "./kubectl-klock"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-klock"

  - selector:
      matchLabels:
        os: linux
        arch: "arm64"
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/kubectl-klock_linux_arm64.tar.gz" .TagName }}
    files:
    - from: "./kubectl-klock"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-klock"

  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/kubectl-klock_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "./kubectl-klock"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-klock"

  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/kubectl-klock_darwin_arm64.tar.gz" .TagName }}
    files:
    - from: "./kubectl-klock"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-klock"

  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/kubectl-klock_windows_amd64.zip" .TagName }}
    files:
    - from: "/kubectl-klock.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-klock.exe"

  - selector:
      matchLabels:
        os: windows
        arch: "386"
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/kubectl-klock_windows_386.zip" .TagName }}
    files:
    - from: "/kubectl-klock.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-klock.exe"

  - selector:
      matchLabels:
        os: windows
        arch: arm64
    {{addURIAndSha "https://github.com/jilleJr/kubectl-klock/releases/download/{{ .TagName }}/kubectl-klock_windows_arm64.zip" .TagName }}
    files:
    - from: "/kubectl-klock.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "kubectl-klock.exe"

  shortDescription: Watches resources
  description: |
    Watches resources and prints them in a human-readable manner.
    Very similar to `kubectl get`, but with live updates.
