apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: klock
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/jilleJr/kubectl-klock/releases/download/v0.1.0/klock_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./klock"
      to: "."
    - from: LICENSE
      to: "."
    bin: "klock"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/jilleJr/kubectl-klock/releases/download/v0.1.0/klock_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./klock"
      to: "."
    - from: LICENSE
      to: "."
    bin: "klock"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/jilleJr/kubectl-klock/releases/download/v0.1.0/klock_windows_amd64.zip
    sha256: ""
    files:
    - from: "/klock.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "klock.exe"
  shortDescription: A new plugin
  homepage: https://github.com/jilleJr/kubectl-klock
  caveats: |
    Usage:
      $ kubectl klock

    For additional options:
      $ kubectl klock --help
      or https://github.com/jilleJr/kubectl-klock/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
