# SPDX-FileCopyrightText: 2021 Wharf (Iver Sverige AB)
#
# SPDX-License-Identifier: MIT

name: Go format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  goimports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Format all .go files
        run:
          echo "Checking files:"
          find . -name '*.go' -not -path './api/**'
          goimports -w $(find . -name '*.go' -not -path './api/**')

      - uses: reviewdog/action-suggester@aa38384ceb608d00f84b4690cacc83a5aba307ff # v1.24.0
        with:
          tool_name: goimports
