# SPDX-FileCopyrightText: 2019 Replicated, Inc.
#
# SPDX-License-Identifier: Apache-2.0

name: release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: false

      - name: Setup Snapcraft
        uses: samuelmeuli/action-snapcraft@fceeb3c308e76f3487e72ef608618de625fb7fe8 # v3.0.1

      - name: Create Snapcraft cache dirs
        run: |
          mkdir -pv "$HOME/.cache/snapcraft/download"
          mkdir -pv "$HOME/.cache/snapcraft/stage-packages"

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ~> v2
          args: release --clean

      - name: Attest release artifacts
        uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4.2.2
        with:
          subject-path: |
            dist/kubectl-klock_*.tar.gz
            dist/kubectl-klock_*.zip
            dist/kubectl-klock_*/*

      - name: Update new version in krew-index
        uses: rajatjindal/krew-release-bot@c970b8a8f6dbc2f2285a26e3ae160903b87002c3 # v0.0.51

      - name: Publish Snaps to the Snap Store (stable channel)
        run: for snap in $(ls dist/*.snap); do snapcraft upload --release=edge $snap; done
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
