# SPDX-FileCopyrightText: 2019 Replicated, Inc.
#
# SPDX-License-Identifier: Apache-2.0

name: test
on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod

      - name: Run tests
        run: |
          go test -v ./...
